### PR TITLE
Use serializers.Serializer to mixin with plain Serializer

### PR DESCRIPTION
**Pull request by phillbaker**
So that serializers which don't inherit from `ModelSerializer` can use this functionality.

In retrospect - this would be a breaking change. Any thoughts on how to approach this gracefully?

An example:
```
# using a plain serializer
class FooSerializerV3(BaseVersioningSerializer):
    test_field_two = serializers.CharField()

# using model serializer
class TestSerializerV3(serializers.ModelSerializer, BaseVersioningSerializer):
    transform_base = 'tests.test_transforms.TestModelTransform'

    class Meta:
        model = TestModelV3
        fields = (
            'test_field_two',
            'test_field_three',
            'test_field_four',
            'test_field_five',
            'new_test_field',
            'new_related_object_id_list',
        )
```

### CODE REVIEW

**Comment by mrhwick** [comment]
I like your idea of using multiple inheritance here, and I don't think it will incur any obvious incompatibilities.

Have you tried fixing those broken tests by making sure the test serializers are inheriting from `serializers.ModelSerializer` now that it isn't being inherited by association from `BaseVersioningSerializer`?

**Comment by phillbaker** [comment]
Thanks for the feedback! I'll fix up those tests and any documentation that might also need to be updated.

**Comment by mrhwick** [comment]
You could also add in a smaller set of tests that gives us the same guarantees about basic serializers (inheriting only from `Serializer`) as we currently have with the full model serializer tests. That would make me feel comfortable about my assumption that we wouldn't be causing problems for those that use that newly available configuration.

**Comment by phillbaker** [comment]
Updated to follow your suggestions - I had to add a couple of non-related commits to get this green on travis.

**Comment by mrhwick** [comment]
I'll be able to take a look at this soon, and should be able to get it merged in ASAP after review. Thanks for submitting a PR!

**Review by mrhwick — APPROVED** [review]

**Comment by mrhwick** [comment]
@phillbaker Apologies for taking so long to merge this. Thank you for the PR, this was excellent work.

**Pull request merged**
